// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//message id
type ID int32

const (
	ID_MSG_BEGIN     ID = 0
	ID_MSG_Connect   ID = 1
	ID_MSG_Heartbeat ID = 2
	ID_MSG_JoinRoom  ID = 10
	ID_MSG_Progress  ID = 11
	ID_MSG_Ready     ID = 12
	ID_MSG_Start     ID = 13
	ID_MSG_Frame     ID = 14
	ID_MSG_Input     ID = 15
	ID_MSG_Result    ID = 16
	ID_MSG_Close     ID = 17
	ID_MSG_END       ID = 20
)

var ID_name = map[int32]string{
	0:  "MSG_BEGIN",
	1:  "MSG_Connect",
	2:  "MSG_Heartbeat",
	10: "MSG_JoinRoom",
	11: "MSG_Progress",
	12: "MSG_Ready",
	13: "MSG_Start",
	14: "MSG_Frame",
	15: "MSG_Input",
	16: "MSG_Result",
	17: "MSG_Close",
	20: "MSG_END",
}

var ID_value = map[string]int32{
	"MSG_BEGIN":     0,
	"MSG_Connect":   1,
	"MSG_Heartbeat": 2,
	"MSG_JoinRoom":  10,
	"MSG_Progress":  11,
	"MSG_Ready":     12,
	"MSG_Start":     13,
	"MSG_Frame":     14,
	"MSG_Input":     15,
	"MSG_Result":    16,
	"MSG_Close":     17,
	"MSG_END":       20,
}

func (x ID) String() string {
	return proto.EnumName(ID_name, int32(x))
}

func (ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

//error code
type ERROR_CODE int32

const (
	ERROR_CODE_ERR_Ok        ERROR_CODE = 0
	ERROR_CODE_ERR_NoPlayer  ERROR_CODE = 1
	ERROR_CODE_ERR_NoRoom    ERROR_CODE = 2
	ERROR_CODE_ERR_RoomState ERROR_CODE = 3
	ERROR_CODE_ERR_Token     ERROR_CODE = 4
)

var ERROR_CODE_name = map[int32]string{
	0: "ERR_Ok",
	1: "ERR_NoPlayer",
	2: "ERR_NoRoom",
	3: "ERR_RoomState",
	4: "ERR_Token",
}

var ERROR_CODE_value = map[string]int32{
	"ERR_Ok":        0,
	"ERR_NoPlayer":  1,
	"ERR_NoRoom":    2,
	"ERR_RoomState": 3,
	"ERR_Token":     4,
}

func (x ERROR_CODE) String() string {
	return proto.EnumName(ERROR_CODE_name, int32(x))
}

func (ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

//connect message, first message from client side
type C2S_ConnectMsg struct {
	PlayerID             uint64   `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	BattleID             uint64   `protobuf:"varint,2,opt,name=battleID,proto3" json:"battleID,omitempty"`
	Token                string   `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_ConnectMsg) Reset()         { *m = C2S_ConnectMsg{} }
func (m *C2S_ConnectMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_ConnectMsg) ProtoMessage()    {}
func (*C2S_ConnectMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *C2S_ConnectMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_ConnectMsg.Unmarshal(m, b)
}
func (m *C2S_ConnectMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_ConnectMsg.Marshal(b, m, deterministic)
}
func (m *C2S_ConnectMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_ConnectMsg.Merge(m, src)
}
func (m *C2S_ConnectMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_ConnectMsg.Size(m)
}
func (m *C2S_ConnectMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_ConnectMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_ConnectMsg proto.InternalMessageInfo

func (m *C2S_ConnectMsg) GetPlayerID() uint64 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *C2S_ConnectMsg) GetBattleID() uint64 {
	if m != nil {
		return m.BattleID
	}
	return 0
}

func (m *C2S_ConnectMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//connect message from server side (S2C)
type S2C_ConnectMsg struct {
	ErrorCode            ERROR_CODE `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2C_ConnectMsg) Reset()         { *m = S2C_ConnectMsg{} }
func (m *S2C_ConnectMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_ConnectMsg) ProtoMessage()    {}
func (*S2C_ConnectMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *S2C_ConnectMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_ConnectMsg.Unmarshal(m, b)
}
func (m *S2C_ConnectMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_ConnectMsg.Marshal(b, m, deterministic)
}
func (m *S2C_ConnectMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_ConnectMsg.Merge(m, src)
}
func (m *S2C_ConnectMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_ConnectMsg.Size(m)
}
func (m *S2C_ConnectMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_ConnectMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_ConnectMsg proto.InternalMessageInfo

func (m *S2C_ConnectMsg) GetErrorCode() ERROR_CODE {
	if m != nil {
		return m.ErrorCode
	}
	return ERROR_CODE_ERR_Ok
}

//join room message (S2C)
type S2C_JoinRoomMsg struct {
	RoomSeatId           int32    `protobuf:"varint,1,opt,name=roomSeatId,proto3" json:"roomSeatId,omitempty"`
	Others               []uint64 `protobuf:"varint,2,rep,packed,name=others,proto3" json:"others,omitempty"`
	Pros                 []int32  `protobuf:"varint,3,rep,packed,name=pros,proto3" json:"pros,omitempty"`
	RandomSeed           int32    `protobuf:"varint,4,opt,name=randomSeed,proto3" json:"randomSeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_JoinRoomMsg) Reset()         { *m = S2C_JoinRoomMsg{} }
func (m *S2C_JoinRoomMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_JoinRoomMsg) ProtoMessage()    {}
func (*S2C_JoinRoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *S2C_JoinRoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_JoinRoomMsg.Unmarshal(m, b)
}
func (m *S2C_JoinRoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_JoinRoomMsg.Marshal(b, m, deterministic)
}
func (m *S2C_JoinRoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_JoinRoomMsg.Merge(m, src)
}
func (m *S2C_JoinRoomMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_JoinRoomMsg.Size(m)
}
func (m *S2C_JoinRoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_JoinRoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_JoinRoomMsg proto.InternalMessageInfo

func (m *S2C_JoinRoomMsg) GetRoomSeatId() int32 {
	if m != nil {
		return m.RoomSeatId
	}
	return 0
}

func (m *S2C_JoinRoomMsg) GetOthers() []uint64 {
	if m != nil {
		return m.Others
	}
	return nil
}

func (m *S2C_JoinRoomMsg) GetPros() []int32 {
	if m != nil {
		return m.Pros
	}
	return nil
}

func (m *S2C_JoinRoomMsg) GetRandomSeed() int32 {
	if m != nil {
		return m.RandomSeed
	}
	return 0
}

//game start message (S2C)
type S2C_StartMsg struct {
	TimeStamp            int64    `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_StartMsg) Reset()         { *m = S2C_StartMsg{} }
func (m *S2C_StartMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_StartMsg) ProtoMessage()    {}
func (*S2C_StartMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *S2C_StartMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_StartMsg.Unmarshal(m, b)
}
func (m *S2C_StartMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_StartMsg.Marshal(b, m, deterministic)
}
func (m *S2C_StartMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_StartMsg.Merge(m, src)
}
func (m *S2C_StartMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_StartMsg.Size(m)
}
func (m *S2C_StartMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_StartMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_StartMsg proto.InternalMessageInfo

func (m *S2C_StartMsg) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

//read progress (C2S)
type C2S_ProgressMsg struct {
	Pro                  int32    `protobuf:"varint,1,opt,name=pro,proto3" json:"pro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_ProgressMsg) Reset()         { *m = C2S_ProgressMsg{} }
func (m *C2S_ProgressMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_ProgressMsg) ProtoMessage()    {}
func (*C2S_ProgressMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *C2S_ProgressMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_ProgressMsg.Unmarshal(m, b)
}
func (m *C2S_ProgressMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_ProgressMsg.Marshal(b, m, deterministic)
}
func (m *C2S_ProgressMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_ProgressMsg.Merge(m, src)
}
func (m *C2S_ProgressMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_ProgressMsg.Size(m)
}
func (m *C2S_ProgressMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_ProgressMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_ProgressMsg proto.InternalMessageInfo

func (m *C2S_ProgressMsg) GetPro() int32 {
	if m != nil {
		return m.Pro
	}
	return 0
}

//read progress (S2C)
type S2C_ProgressMsg struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pro                  int32    `protobuf:"varint,2,opt,name=pro,proto3" json:"pro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_ProgressMsg) Reset()         { *m = S2C_ProgressMsg{} }
func (m *S2C_ProgressMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_ProgressMsg) ProtoMessage()    {}
func (*S2C_ProgressMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *S2C_ProgressMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_ProgressMsg.Unmarshal(m, b)
}
func (m *S2C_ProgressMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_ProgressMsg.Marshal(b, m, deterministic)
}
func (m *S2C_ProgressMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_ProgressMsg.Merge(m, src)
}
func (m *S2C_ProgressMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_ProgressMsg.Size(m)
}
func (m *S2C_ProgressMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_ProgressMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_ProgressMsg proto.InternalMessageInfo

func (m *S2C_ProgressMsg) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2C_ProgressMsg) GetPro() int32 {
	if m != nil {
		return m.Pro
	}
	return 0
}

//client input message (C2S)
type C2S_InputMsg struct {
	Sid                  int32    `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	FrameID              uint32   `protobuf:"varint,4,opt,name=frameID,proto3" json:"frameID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_InputMsg) Reset()         { *m = C2S_InputMsg{} }
func (m *C2S_InputMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_InputMsg) ProtoMessage()    {}
func (*C2S_InputMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *C2S_InputMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_InputMsg.Unmarshal(m, b)
}
func (m *C2S_InputMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_InputMsg.Marshal(b, m, deterministic)
}
func (m *C2S_InputMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_InputMsg.Merge(m, src)
}
func (m *C2S_InputMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_InputMsg.Size(m)
}
func (m *C2S_InputMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_InputMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_InputMsg proto.InternalMessageInfo

func (m *C2S_InputMsg) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *C2S_InputMsg) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *C2S_InputMsg) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *C2S_InputMsg) GetFrameID() uint32 {
	if m != nil {
		return m.FrameID
	}
	return 0
}

//frame input data
type InputData struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sid                  int32    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	RoomSeatId           int32    `protobuf:"varint,5,opt,name=roomSeatId,proto3" json:"roomSeatId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputData) Reset()         { *m = InputData{} }
func (m *InputData) String() string { return proto.CompactTextString(m) }
func (*InputData) ProtoMessage()    {}
func (*InputData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *InputData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputData.Unmarshal(m, b)
}
func (m *InputData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputData.Marshal(b, m, deterministic)
}
func (m *InputData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputData.Merge(m, src)
}
func (m *InputData) XXX_Size() int {
	return xxx_messageInfo_InputData.Size(m)
}
func (m *InputData) XXX_DiscardUnknown() {
	xxx_messageInfo_InputData.DiscardUnknown(m)
}

var xxx_messageInfo_InputData proto.InternalMessageInfo

func (m *InputData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InputData) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *InputData) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *InputData) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *InputData) GetRoomSeatId() int32 {
	if m != nil {
		return m.RoomSeatId
	}
	return 0
}

//frame data
type FrameData struct {
	FrameID              uint32       `protobuf:"varint,1,opt,name=frameID,proto3" json:"frameID,omitempty"`
	Input                []*InputData `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FrameData) Reset()         { *m = FrameData{} }
func (m *FrameData) String() string { return proto.CompactTextString(m) }
func (*FrameData) ProtoMessage()    {}
func (*FrameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *FrameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameData.Unmarshal(m, b)
}
func (m *FrameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameData.Marshal(b, m, deterministic)
}
func (m *FrameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameData.Merge(m, src)
}
func (m *FrameData) XXX_Size() int {
	return xxx_messageInfo_FrameData.Size(m)
}
func (m *FrameData) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameData.DiscardUnknown(m)
}

var xxx_messageInfo_FrameData proto.InternalMessageInfo

func (m *FrameData) GetFrameID() uint32 {
	if m != nil {
		return m.FrameID
	}
	return 0
}

func (m *FrameData) GetInput() []*InputData {
	if m != nil {
		return m.Input
	}
	return nil
}

//cast frame data (S2C)
type S2C_FrameMsg struct {
	Frames               []*FrameData `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2C_FrameMsg) Reset()         { *m = S2C_FrameMsg{} }
func (m *S2C_FrameMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_FrameMsg) ProtoMessage()    {}
func (*S2C_FrameMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *S2C_FrameMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_FrameMsg.Unmarshal(m, b)
}
func (m *S2C_FrameMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_FrameMsg.Marshal(b, m, deterministic)
}
func (m *S2C_FrameMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_FrameMsg.Merge(m, src)
}
func (m *S2C_FrameMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_FrameMsg.Size(m)
}
func (m *S2C_FrameMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_FrameMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_FrameMsg proto.InternalMessageInfo

func (m *S2C_FrameMsg) GetFrames() []*FrameData {
	if m != nil {
		return m.Frames
	}
	return nil
}

//result (C2S)
type C2S_ResultMsg struct {
	WinnerID             uint64   `protobuf:"varint,1,opt,name=winnerID,proto3" json:"winnerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_ResultMsg) Reset()         { *m = C2S_ResultMsg{} }
func (m *C2S_ResultMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_ResultMsg) ProtoMessage()    {}
func (*C2S_ResultMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *C2S_ResultMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_ResultMsg.Unmarshal(m, b)
}
func (m *C2S_ResultMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_ResultMsg.Marshal(b, m, deterministic)
}
func (m *C2S_ResultMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_ResultMsg.Merge(m, src)
}
func (m *C2S_ResultMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_ResultMsg.Size(m)
}
func (m *C2S_ResultMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_ResultMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_ResultMsg proto.InternalMessageInfo

func (m *C2S_ResultMsg) GetWinnerID() uint64 {
	if m != nil {
		return m.WinnerID
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.ID", ID_name, ID_value)
	proto.RegisterEnum("pb.ERROR_CODE", ERROR_CODE_name, ERROR_CODE_value)
	proto.RegisterType((*C2S_ConnectMsg)(nil), "pb.C2S_ConnectMsg")
	proto.RegisterType((*S2C_ConnectMsg)(nil), "pb.S2C_ConnectMsg")
	proto.RegisterType((*S2C_JoinRoomMsg)(nil), "pb.S2C_JoinRoomMsg")
	proto.RegisterType((*S2C_StartMsg)(nil), "pb.S2C_StartMsg")
	proto.RegisterType((*C2S_ProgressMsg)(nil), "pb.C2S_ProgressMsg")
	proto.RegisterType((*S2C_ProgressMsg)(nil), "pb.S2C_ProgressMsg")
	proto.RegisterType((*C2S_InputMsg)(nil), "pb.C2S_InputMsg")
	proto.RegisterType((*InputData)(nil), "pb.InputData")
	proto.RegisterType((*FrameData)(nil), "pb.FrameData")
	proto.RegisterType((*S2C_FrameMsg)(nil), "pb.S2C_FrameMsg")
	proto.RegisterType((*C2S_ResultMsg)(nil), "pb.C2S_ResultMsg")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0xad, 0xed, 0x24, 0x5d, 0x6e, 0x62, 0x47, 0x15, 0x65, 0x98, 0x31, 0x46, 0x70, 0x19, 0x84,
	0xae, 0xf4, 0x21, 0x65, 0xaf, 0x7b, 0x58, 0x9c, 0x75, 0x2e, 0xf4, 0x03, 0x79, 0xec, 0x69, 0x2c,
	0x28, 0xb3, 0xd6, 0x99, 0xc6, 0x96, 0x91, 0x55, 0xd6, 0x3c, 0xec, 0xd7, 0xed, 0x8f, 0x8d, 0x2b,
	0x5b, 0xf9, 0x28, 0x7b, 0xd3, 0xb9, 0xf2, 0x3d, 0xe7, 0xdc, 0x0f, 0x19, 0xfc, 0x42, 0xd4, 0x35,
	0xbf, 0x17, 0xe7, 0x95, 0x92, 0x5a, 0x52, 0xb7, 0x5a, 0x46, 0xdf, 0x21, 0x98, 0x4d, 0xd3, 0xc5,
	0x4c, 0x96, 0xa5, 0xf8, 0xa1, 0xaf, 0xeb, 0x7b, 0xfa, 0x0a, 0x5e, 0x54, 0x2b, 0xbe, 0x16, 0x2a,
	0x89, 0x43, 0x67, 0xec, 0x4c, 0x3a, 0x6c, 0x83, 0xf1, 0x6e, 0xc9, 0xb5, 0x5e, 0x89, 0x24, 0x0e,
	0xdd, 0xe6, 0xce, 0x62, 0x7a, 0x0c, 0x5d, 0x2d, 0x1f, 0x44, 0x19, 0xc2, 0xd8, 0x99, 0xf4, 0x59,
	0x03, 0xa2, 0x0f, 0x10, 0xa4, 0xd3, 0xd9, 0x2e, 0xff, 0x19, 0xf4, 0x85, 0x52, 0x52, 0xcd, 0x64,
	0x26, 0x8c, 0x40, 0x30, 0x0d, 0xce, 0xab, 0xe5, 0xf9, 0x9c, 0xb1, 0x5b, 0xb6, 0x98, 0xdd, 0xc6,
	0x73, 0xb6, 0xfd, 0x20, 0xfa, 0x03, 0x23, 0xcc, 0xbf, 0x92, 0x79, 0xc9, 0xa4, 0x2c, 0x90, 0xe0,
	0x0d, 0x80, 0x92, 0xb2, 0x48, 0x05, 0xd7, 0x49, 0x66, 0x18, 0xba, 0x6c, 0x27, 0x42, 0x5f, 0x42,
	0x4f, 0xea, 0x5f, 0x42, 0xd5, 0xa1, 0x3b, 0xf6, 0x26, 0x1d, 0xd6, 0x22, 0x4a, 0xa1, 0x53, 0x29,
	0x59, 0x87, 0xde, 0xd8, 0x9b, 0x74, 0x99, 0x39, 0x1b, 0x2e, 0x5e, 0x66, 0x98, 0x2b, 0xb2, 0xb0,
	0xd3, 0x72, 0x6d, 0x22, 0xd1, 0x19, 0x0c, 0x51, 0x3e, 0xd5, 0x5c, 0x19, 0xf3, 0xaf, 0xa1, 0xaf,
	0xf3, 0x42, 0xa4, 0x9a, 0x17, 0x95, 0x91, 0xf6, 0xd8, 0x36, 0x10, 0x9d, 0xc0, 0x08, 0x9b, 0x79,
	0xa7, 0xe4, 0xbd, 0x12, 0x75, 0x8d, 0x09, 0x04, 0xbc, 0x4a, 0xc9, 0xd6, 0x25, 0x1e, 0xa3, 0x8b,
	0xa6, 0xa2, 0xdd, 0x8f, 0x02, 0x70, 0xf3, 0xac, 0x6d, 0xb6, 0x9b, 0x67, 0x36, 0xc9, 0xdd, 0x26,
	0x7d, 0x85, 0x21, 0x32, 0x27, 0x65, 0xf5, 0xa8, 0x5b, 0xda, 0x3a, 0xb7, 0xc5, 0xe3, 0x91, 0x0e,
	0xc1, 0x79, 0x6a, 0x33, 0x9c, 0x27, 0x44, 0xeb, 0xd0, 0x6b, 0xd0, 0x9a, 0x86, 0x70, 0xf8, 0x53,
	0xf1, 0x02, 0xa7, 0x86, 0x25, 0xfa, 0xcc, 0xc2, 0x28, 0x87, 0xbe, 0xe1, 0x8c, 0xb9, 0xe6, 0xff,
	0xb3, 0x81, 0x22, 0xee, 0x33, 0x11, 0x6f, 0x4f, 0xa4, 0x63, 0x45, 0xf6, 0xc7, 0xd2, 0x7d, 0x3e,
	0x96, 0xe8, 0x0a, 0xfa, 0x9f, 0x50, 0xd5, 0x48, 0xed, 0x38, 0x72, 0xf6, 0x1c, 0xd1, 0x13, 0xe8,
	0xe6, 0xe8, 0xc8, 0x0c, 0x6f, 0x30, 0xf5, 0x71, 0x35, 0x36, 0x16, 0x59, 0x73, 0x17, 0xbd, 0x6f,
	0xc6, 0x62, 0xf8, 0xb0, 0x1d, 0x6f, 0xa1, 0x67, 0xf2, 0xeb, 0xd0, 0xd9, 0x66, 0x6d, 0xd4, 0x58,
	0x7b, 0x19, 0xbd, 0x03, 0x1f, 0xbb, 0xc8, 0x44, 0xfd, 0xb8, 0xb2, 0xbb, 0xfe, 0x3b, 0x2f, 0xcb,
	0xdd, 0x5d, 0xb7, 0xf8, 0xf4, 0xaf, 0x03, 0x6e, 0x12, 0x53, 0x1f, 0xfa, 0xd7, 0xe9, 0xe5, 0xe2,
	0xe3, 0xfc, 0x32, 0xb9, 0x21, 0x07, 0x74, 0x04, 0x03, 0x84, 0xed, 0x3e, 0x13, 0x87, 0x1e, 0x81,
	0x8f, 0x81, 0xcf, 0x82, 0x2b, 0xbd, 0x14, 0x5c, 0x13, 0x97, 0x12, 0x18, 0x62, 0xc8, 0xee, 0x2c,
	0x01, 0x1b, 0xb1, 0x33, 0x27, 0x03, 0x4b, 0xcb, 0x04, 0xcf, 0xd6, 0x64, 0x68, 0xa1, 0xd9, 0x33,
	0xe2, 0x5b, 0x68, 0x2a, 0x20, 0x81, 0x85, 0xa6, 0x0d, 0x64, 0x44, 0x03, 0x80, 0x26, 0x17, 0xcb,
	0x20, 0xc4, 0x5e, 0xcf, 0x56, 0xb2, 0x16, 0xe4, 0x88, 0x0e, 0xe0, 0x10, 0xe1, 0xfc, 0x26, 0x26,
	0xc7, 0xa7, 0xdf, 0x00, 0xb6, 0x0f, 0x8b, 0x02, 0xf4, 0xe6, 0x8c, 0x2d, 0x6e, 0x1f, 0xc8, 0x01,
	0x7a, 0xc2, 0xf3, 0x8d, 0xbc, 0x33, 0xaf, 0x9b, 0x38, 0xc8, 0xdb, 0x44, 0x8c, 0x6b, 0x17, 0x4b,
	0x43, 0x8c, 0x28, 0xd5, 0x5c, 0x0b, 0xe2, 0xa1, 0x14, 0x86, 0xbe, 0xe0, 0xdb, 0x26, 0x9d, 0x65,
	0xcf, 0xfc, 0x48, 0x2e, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x09, 0x9c, 0x66, 0x48, 0x59, 0x04,
	0x00, 0x00,
}
